#!/bin/sh

# Include the wrappers utility script
. /usr/lib/java-wrappers/java-wrappers.sh

# We need openjdk or sun6
find_java_runtime openjdk sun6

find_jars activation axis jalview-castor-1.1-cycle-xml \
    jalview-commons-discovery jalview-commons-logging jaxrpc \
    jhall jalview-Jmol-11.0.2 log4j-1.2 \
    gnumail jalview-regex saaj jalview-vamsas-client \
    wsdl4j xercesImpl xml-apis \
    jalview

run_java jalview.bin.Jalview "$@"
