#!/bin/sh
# autopkgtest check: take an example input file and have outputs in different
# formats, to be compared with reference ones..
# (C) 2020-2021 Pierre Gruet.
# Author: Pierre Gruet <pgtdebian@free.fr>

set -e

SOURCEDIR=$(pwd)
WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

jalview -nodisplay -jvmmemmax=512m -open $SOURCEDIR/examples/uniref50.fa -blc uniref50_out.blc
jalview -nodisplay -jvmmemmax=512m -open $SOURCEDIR/examples/uniref50.fa -fasta uniref50_out.mfa
jalview -nodisplay -jvmmemmax=512m -open $SOURCEDIR/examples/uniref50.fa -pfam uniref50_out.pfam
jalview -nodisplay -jvmmemmax=512m -open $SOURCEDIR/examples/uniref50.fa -pir uniref50_out.pir
jalview -nodisplay -jvmmemmax=512m -open $SOURCEDIR/examples/uniref50.fa -clustal uniref50_out1.aln
jalview -nodisplay -jvmmemmax=512m -open $SOURCEDIR/examples/uniref50.fa -pileup uniref50_out2.aln

diff uniref50_out.blc $SOURCEDIR/debian/tests/expectedOutputs/test_uniref50_out.blc

if [ $? -ne 0 ]; then
  exit 1
fi

diff uniref50_out.mfa $SOURCEDIR/debian/tests/expectedOutputs/test_uniref50_out.mfa

if [ $? -ne 0 ]; then
  exit 1
fi

diff uniref50_out.pfam $SOURCEDIR/debian/tests/expectedOutputs/test_uniref50_out.pfam

if [ $? -ne 0 ]; then
  exit 1
fi

diff uniref50_out.pir $SOURCEDIR/debian/tests/expectedOutputs/test_uniref50_out.pir

if [ $? -ne 0 ]; then
  exit 1
fi

diff uniref50_out1.aln $SOURCEDIR/debian/tests/expectedOutputs/test_uniref50_out1.aln

if [ $? -ne 0 ]; then
  exit 1
fi

diff uniref50_out2.aln $SOURCEDIR/debian/tests/expectedOutputs/test_uniref50_out2.aln

if [ $? -ne 0 ]; then
  exit 1
fi
