//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 02:21:15 PM BST 
//


package jalview.xml.binding.jalview;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alcodon" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="pos1" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="pos2" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="pos3" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="alcodMap" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{www.vamsas.ac.uk/jalview/version2}Mapping"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="dnasq" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alcodon",
    "alcodMap"
})
@XmlRootElement(name = "AlcodonFrame")
public class AlcodonFrame {

    protected List<AlcodonFrame.Alcodon> alcodon;
    protected List<AlcodonFrame.AlcodMap> alcodMap;

    /**
     * Gets the value of the alcodon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alcodon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlcodon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlcodonFrame.Alcodon }
     * 
     * 
     */
    public List<AlcodonFrame.Alcodon> getAlcodon() {
        if (alcodon == null) {
            alcodon = new ArrayList<AlcodonFrame.Alcodon>();
        }
        return this.alcodon;
    }

    /**
     * Gets the value of the alcodMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alcodMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlcodMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlcodonFrame.AlcodMap }
     * 
     * 
     */
    public List<AlcodonFrame.AlcodMap> getAlcodMap() {
        if (alcodMap == null) {
            alcodMap = new ArrayList<AlcodonFrame.AlcodMap>();
        }
        return this.alcodMap;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{www.vamsas.ac.uk/jalview/version2}Mapping"/>
     *       &lt;/sequence>
     *       &lt;attribute name="dnasq" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mapping"
    })
    public static class AlcodMap {

        @XmlElement(name = "Mapping", required = true)
        protected Mapping mapping;
        @XmlAttribute(name = "dnasq", required = true)
        protected String dnasq;

        /**
         * 
         * 										a Mapping entry and an associated protein sequence
         * 									
         * 
         * @return
         *     possible object is
         *     {@link Mapping }
         *     
         */
        public Mapping getMapping() {
            return mapping;
        }

        /**
         * Sets the value of the mapping property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mapping }
         *     
         */
        public void setMapping(Mapping value) {
            this.mapping = value;
        }

        /**
         * Gets the value of the dnasq property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDnasq() {
            return dnasq;
        }

        /**
         * Sets the value of the dnasq property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDnasq(String value) {
            this.dnasq = value;
        }

    }


    /**
     * 
     * 								specifies a series of aligned codons from an associated DNA sequence alignment that when translated correspond to columns of a peptide alignment.
     * 								Element may have either all pos1,2,3 attributes specified, or none at all (indicating a gapped column with no translated peptide).
     * 							
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="pos1" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="pos2" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="pos3" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Alcodon {

        @XmlAttribute(name = "pos1")
        protected BigInteger pos1;
        @XmlAttribute(name = "pos2")
        protected BigInteger pos2;
        @XmlAttribute(name = "pos3")
        protected BigInteger pos3;

        /**
         * Gets the value of the pos1 property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPos1() {
            return pos1;
        }

        /**
         * Sets the value of the pos1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPos1(BigInteger value) {
            this.pos1 = value;
        }

        /**
         * Gets the value of the pos2 property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPos2() {
            return pos2;
        }

        /**
         * Sets the value of the pos2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPos2(BigInteger value) {
            this.pos2 = value;
        }

        /**
         * Gets the value of the pos3 property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPos3() {
            return pos3;
        }

        /**
         * Sets the value of the pos3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPos3(BigInteger value) {
            this.pos3 = value;
        }

    }

}
