//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 02:21:15 PM BST 
//


package jalview.xml.binding.jalview;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A feature match condition, which may be simple or compound
 * 
 * <p>Java class for FeatureMatcherSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureMatcherSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="matchCondition" type="{www.jalview.org/colours}FeatureMatcher"/>
 *         &lt;element name="compoundMatcher">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="matcherSet" type="{www.jalview.org/colours}FeatureMatcherSet" maxOccurs="2" minOccurs="2"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="and" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureMatcherSet", namespace = "www.jalview.org/colours", propOrder = {
    "matchCondition",
    "compoundMatcher"
})
public class FeatureMatcherSet {

    @XmlElement(namespace = "")
    protected FeatureMatcher matchCondition;
    @XmlElement(namespace = "")
    protected FeatureMatcherSet.CompoundMatcher compoundMatcher;

    /**
     * Gets the value of the matchCondition property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureMatcher }
     *     
     */
    public FeatureMatcher getMatchCondition() {
        return matchCondition;
    }

    /**
     * Sets the value of the matchCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureMatcher }
     *     
     */
    public void setMatchCondition(FeatureMatcher value) {
        this.matchCondition = value;
    }

    /**
     * Gets the value of the compoundMatcher property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureMatcherSet.CompoundMatcher }
     *     
     */
    public FeatureMatcherSet.CompoundMatcher getCompoundMatcher() {
        return compoundMatcher;
    }

    /**
     * Sets the value of the compoundMatcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureMatcherSet.CompoundMatcher }
     *     
     */
    public void setCompoundMatcher(FeatureMatcherSet.CompoundMatcher value) {
        this.compoundMatcher = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="matcherSet" type="{www.jalview.org/colours}FeatureMatcherSet" maxOccurs="2" minOccurs="2"/>
     *       &lt;/sequence>
     *       &lt;attribute name="and" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "matcherSet"
    })
    public static class CompoundMatcher {

        @XmlElement(namespace = "", required = true)
        protected List<FeatureMatcherSet> matcherSet;
        @XmlAttribute(name = "and", required = true)
        protected boolean and;

        /**
         * Gets the value of the matcherSet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the matcherSet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMatcherSet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureMatcherSet }
         * 
         * 
         */
        public List<FeatureMatcherSet> getMatcherSet() {
            if (matcherSet == null) {
                matcherSet = new ArrayList<FeatureMatcherSet>();
            }
            return this.matcherSet;
        }

        /**
         * Gets the value of the and property.
         * 
         */
        public boolean isAnd() {
            return and;
        }

        /**
         * Sets the value of the and property.
         * 
         */
        public void setAnd(boolean value) {
            this.and = value;
        }

    }

}
