//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 02:21:15 PM BST 
//


package jalview.xml.binding.jalview;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{www.vamsas.ac.uk/jalview/version2}SequenceType">
 *       &lt;sequence>
 *         &lt;element name="DBRef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{www.vamsas.ac.uk/jalview/version2}Mapping" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="accessionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="locus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="dsseqid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="biotype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbRef"
})
@XmlRootElement(name = "Sequence")
public class Sequence
    extends SequenceType
{

    @XmlElement(name = "DBRef")
    protected List<Sequence.DBRef> dbRef;
    @XmlAttribute(name = "dsseqid")
    protected String dsseqid;
    @XmlAttribute(name = "biotype")
    protected String biotype;

    /**
     * Gets the value of the dbRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDBRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sequence.DBRef }
     * 
     * 
     */
    public List<Sequence.DBRef> getDBRef() {
        if (dbRef == null) {
            dbRef = new ArrayList<Sequence.DBRef>();
        }
        return this.dbRef;
    }

    /**
     * Gets the value of the dsseqid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsseqid() {
        return dsseqid;
    }

    /**
     * Sets the value of the dsseqid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsseqid(String value) {
        this.dsseqid = value;
    }

    /**
     * Gets the value of the biotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiotype() {
        return biotype;
    }

    /**
     * Sets the value of the biotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiotype(String value) {
        this.biotype = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{www.vamsas.ac.uk/jalview/version2}Mapping" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="accessionId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="locus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mapping"
    })
    public static class DBRef {

        @XmlElement(name = "Mapping")
        protected Mapping mapping;
        @XmlAttribute(name = "source")
        protected String source;
        @XmlAttribute(name = "version")
        protected String version;
        @XmlAttribute(name = "accessionId")
        protected String accessionId;
        @XmlAttribute(name = "locus")
        protected Boolean locus;

        /**
         * Gets the value of the mapping property.
         * 
         * @return
         *     possible object is
         *     {@link Mapping }
         *     
         */
        public Mapping getMapping() {
            return mapping;
        }

        /**
         * Sets the value of the mapping property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mapping }
         *     
         */
        public void setMapping(Mapping value) {
            this.mapping = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the accessionId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessionId() {
            return accessionId;
        }

        /**
         * Sets the value of the accessionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessionId(String value) {
            this.accessionId = value;
        }

        /**
         * Gets the value of the locus property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isLocus() {
            if (locus == null) {
                return false;
            } else {
                return locus;
            }
        }

        /**
         * Sets the value of the locus property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLocus(Boolean value) {
            this.locus = value;
        }

    }

}
