.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Copyright 2011 by Vincent Fourmond
.\" Can be modified and distributed under the terms of the GNU General
.\" public license, version 3 or any later version at your option.
.TH JALVIEW  1  "26-01-2009"
.SH NAME
jalview \- Sequence alignement viewer
.SH SYNOPSIS
.B jalview

.SH DESCRIPTION

.B jalview
provides facilities for viewing/editing and otherwise manipulating
sequence alignments (DNA, amino acids).


.SH JAVA-WRAPPERS NOTE

This program is a shell script wrapper based on
.BR java-wrappers (7).
You therefore benefit from several features; please see the 
.BR java-wrappers (7)
manual page for more information about them.


.SH SEE ALSO

.B http://www.jalview.org

.SH AUTHOR
This manual page was written by Vincent Fourmond <fourmond@debian.org>
from the Debian project, but may be used by others.
